# tester.yml

batch_size: 1
test_size: 1
imsize: 256
version: parsenet
train: false
model_save_path: "face_parsing/models"
#test_image_path: "face_parsing/data"
test_label_path: "mask"
test_color_label_path: "mask"
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
img_path: 'Data_preprocessing/train_img'
label_path: 'Data_preprocessing/train_label'
log_path: 'logs'
log_step: 10
lr_decay: 0.95
model: 'parsenet'
model_name: 'model.pth'
model_save_step: 1.0
num_workers: 2
parallel: False
pretrained_model: None
sample_path: 'samples'
sample_step: 100
total_step: 1000000
use_tensorboard: False